// serviceZones.js
export const SERVICE_ZONES = {
  Damascus: [
    "Al-Hamra",
    "Al Hamra Street",
    "Al-Adawi",
    "Assad Suburb",
    "Al-Baramka",
    "Al-Hariqa",
    "Al-Mezzeh",
    "Baghdad Street",
  ],
  "Reef Dimashq": ["Jaramana", "Qudsaya", "Al-Qutayfah", "Yabroud"],
  Latakia: ["Latakia City", "Latakia Garage", "Qurdaha", "Jableh"],
  Aleppo: ["Aleppo"],
  "Al-Hasakah": ["Al-Hasakah", "Al-Qamishli"],
  "Homs Governorate": [
    "Homs Al-Zahra",
    "Homs Al-Hamra",
    "Homs Al-Hadara",
    "Homs Al-Hawash",
    "Homs Shin",
  ],
  Hama: ["Hama", "Masyaf", "Al-Salamiyah"],
  Tartous: [
    "Tartous",
    "Administration - Al-Rimal",
    "Al-Mahatta",
    "Old Garage",
    "New Garage",
    "Al-Sinaiyaa",
    "Sheikh Saad",
    "Souq Al-Hal",
    "Baniyas",
    "Safita",
    "Drekiesh",
    "Sheikh Badr",
    "Al-Qadmous City",
  ],
  Daraa: ["Daraa City", "Al-Sanamayn"],
};
